### ISSUE TITLE
webView downloads corrupted file when blob url 

### ISSUE THREAD

**Issue by balkarov** [gualtierofrigerio/WKDownloadHelper#1]
Hello.

Thank you for you library. 
I tried to handle blob url and download file from it. For example my blob url: "blob:http://example.com/bd0ae6c8-796c-488e-b691-cee86fa72f04".
But downloadData function return me corrupted file.

I tried to take your last commit with removeBlob method.

PS: In desktop browser file downloading normal.
Sorry I cannot give you example link, because I am testing on local url.

For android I user js method (XMLHttpRequest) for download blob url. But for iOS it does not work.

```swift
webView.evaluateJavaScript("javascript: var xhr = new XMLHttpRequest();" +
            "xhr.open('GET', '" + blobUrl + "', true);" +
            "xhr.setRequestHeader('Content-type','" + mimeType + "');" +
            "xhr.responseType = 'blob';" +
            "xhr.onload = function(e) {" +
            "    if (this.status == 200) {" +
            "        var blob = this.response;" +
            "        var reader = new FileReader();" +
            "        reader.readAsDataURL(blob);" +
            "        reader.onloadend = function() {" +
            "            base64data = reader.result;" +
            "            window.webkit.messageHandlers.callback.postMessage(base64data);" +
            "        }" +
            "    }" +
            "};" +
            "xhr.send();")

```

Does not call in `onload` function.

Any help?

**Comment by gualtierofrigerio** [comment]
So you tried this javascript on a WKWebview and the onload function is never called? Have you tried implementing some of the WKNavigationDelegate methods to find out if there is an error while connecting to the URL?

**Comment by balkarov** [comment]
@gualtierofrigerio  Yes, onload never called. xhr.onerror called with status 0 and empty responseText

**Comment by balkarov** [comment]
And additionally I asked question [on stackoverflow](https://stackoverflow.com/questions/69029847/how-to-handle-blob-url-in-wkwebview-and-download-file)
